import type { StaffProvisioningOperationProfile } from "../types";

export const SCHOOL_PRINCIPAL_OPERATIONS = [
  {
    operationKind: "STUDENT_ATTENDANCE",
    title: "إدارة حضور طلاب المدرسة",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "STUDENT_MEASUREMENT",
    title: "متابعة قياسات طلاب المدرسة",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "STUDENT_TRACKER",
    title: "متابعة سجلات طلاب المدرسة",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "LEARNING_LOSS_FOLLOWUP",
    title: "متابعة الفاقد التعليمي",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "STUDENT_NOTES",
    title: "متابعة ملاحظات الطلاب",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: ["VIEW", "CREATE", "UPDATE_DRAFT", "SUBMIT"],
  },
  {
    operationKind: "STUDENT_CASE_HANDLING",
    title: "متابعة إحالات وحالات الطلاب",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "CASE",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "STUDENT_ACTIVITY_MANAGEMENT",
    title: "إدارة أنشطة المدرسة",
    coverageMode: "ALL_CLASSES_IN_SCOPE",
    targetKind: "STUDENT",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
  {
    operationKind: "STAFF_EVALUATION",
    title: "تقييم موظفي المدرسة",
    coverageMode: "SINGLE_SCOPE",
    targetKind: "STAFF",
    permissions: [
      "VIEW",
      "CREATE",
      "UPDATE_DRAFT",
      "SUBMIT",
      "REVIEW",
      "APPROVE",
    ],
  },
] satisfies StaffProvisioningOperationProfile[];